### PR TITLE
[resource][s]- Refactor Mocked Data Resource

### PR DESCRIPTION
**Pull request by lauragift21**
fixes: #11

### CODE REVIEW

**Comment by anuveyatsu** [comment]
Hey @lauragift21 my understanding is that you have create a `Resource` object which is actually a list of resources - I'd expect it to be a single resource object.

Then, in your template you listing all the resources, however, I think you should have single resource info there.

**Comment by lauragift21** [comment]
Oh okay. I got it will make the changes

**Comment by lauragift21** [comment]
@anuveyatsu just to be clear a data package can have as many resources but for this specific case want only one. 

This is what I mean.

Screenshot 2020-06-08 at 2 32 03 PM

**Comment by anuveyatsu** [comment]
Closing this PR as we're implementing the mocks using `nock` library now.

**Pull request closed without merging**
